import { Command } from "commander";
import { createInterface } from "readline";
import { existsSync, mkdirSync, statSync, writeFileSync } from "fs";
import path from "path";
import { AuthService } from "../services/auth.js";
import { ApiService } from "../services/api.js";
import { Logger } from "../utils/logger.js";
import { GlossaryTermForLang, AiInstructionsResponse } from "../types/index.js";

const SKILL_DIR = "prismy-wording-guidelines";
const SKILL_FILE = "SKILL.md";
const STALE_THRESHOLD_MS = 24 * 60 * 60 * 1000; // 24 hours

const SKILL_FRONTMATTER = `---
name: prismy-wording-guidelines
description: Prismy wording guidelines with approved terminology, tone and style instructions for user-facing text. Use when writing, reviewing or translating UI copy.
---
`;

type PathChoice = {
  label: string;
  paths: string[];
  isSkill: boolean;
};

const PATH_CHOICES: PathChoice[] = [
  {
    label: `Claude Code (.claude/skills/${SKILL_DIR}/${SKILL_FILE})`,
    paths: [`.claude/skills/${SKILL_DIR}/${SKILL_FILE}`],
    isSkill: true,
  },
  {
    label: `Cursor (.cursor/skills/${SKILL_DIR}/${SKILL_FILE})`,
    paths: [`.cursor/skills/${SKILL_DIR}/${SKILL_FILE}`],
    isSkill: true,
  },
  {
    label: "Both Claude Code and Cursor",
    paths: [
      `.claude/skills/${SKILL_DIR}/${SKILL_FILE}`,
      `.cursor/skills/${SKILL_DIR}/${SKILL_FILE}`,
    ],
    isSkill: true,
  },
];

type ContextCommandOptions = {
  language?: string;
  output?: string;
  force?: boolean;
  apiToken?: string;
};

function promptForPaths(): Promise<{ paths: string[]; isSkill: boolean }> {
  const rl = createInterface({ input: process.stdin, output: process.stdout });

  return new Promise((resolve) => {
    Logger.message("\nWhere should we save the wording guidelines?");
    for (let i = 0; i < PATH_CHOICES.length; i++) {
      const suffix = i === 0 ? " (recommended)" : "";
      Logger.message(`  ${i + 1}. ${PATH_CHOICES[i].label}${suffix}`);
    }
    Logger.message(`  ${PATH_CHOICES.length + 1}. Custom path`);

    rl.question(`\nChoose [1-${PATH_CHOICES.length + 1}] (default: 1): `, (answer) => {
      rl.close();
      const choice = parseInt(answer.trim(), 10);
      if (!answer.trim() || choice === 1) {
        resolve(PATH_CHOICES[0]);
      } else if (choice >= 2 && choice <= PATH_CHOICES.length) {
        resolve(PATH_CHOICES[choice - 1]);
      } else if (choice === PATH_CHOICES.length + 1) {
        const rl2 = createInterface({ input: process.stdin, output: process.stdout });
        rl2.question("Enter custom path: ", (customPath) => {
          rl2.close();
          const p = customPath.trim() || PATH_CHOICES[0].paths[0];
          resolve({ paths: [p], isSkill: false });
        });
      } else {
        resolve(PATH_CHOICES[0]);
      }
    });
  });
}

function isStale(filePath: string): boolean {
  try {
    const stats = statSync(filePath);
    return Date.now() - stats.mtimeMs > STALE_THRESHOLD_MS;
  } catch {
    return true;
  }
}

function generateMarkdown(
  glossary: GlossaryTermForLang[],
  aiInstructions: AiInstructionsResponse,
  withFrontmatter: boolean
): string {
  const date = new Date().toISOString().split("T")[0];
  const lines: string[] = [];

  if (withFrontmatter) {
    lines.push(SKILL_FRONTMATTER);
  }

  lines.push("# Prismy Wording Guidelines");
  lines.push("");
  lines.push(`> Auto-generated by \`prismy skills\` on ${date}. Do not edit manually.`);
  lines.push("> Run `prismy skills --force` to refresh.");
  lines.push("");
  lines.push(
    "These are the official wording guidelines for this project, sourced from Prismy. They define approved terminology, tone and style rules for all user-facing text."
  );
  lines.push("");

  // When to Use
  lines.push("## When to Use");
  lines.push("");
  lines.push("- Use this skill when writing or editing user-facing text (UI labels, messages, tooltips, etc.)");
  lines.push("- Use this skill when reviewing translations or suggesting copy changes");
  lines.push("- Use this skill when creating new i18n keys or modifying existing ones");
  lines.push("- Use the ask questions tool if you need to clarify wording requirements with the user");
  lines.push("");
  // Instructions
  lines.push("## Instructions");
  lines.push("");
  lines.push(`> **Auto-update:** This skill was generated on ${date}. If today's date is more than 1 day after that, run \`prismy skills --force\` to refresh it before proceeding.`);
  lines.push("");

  // Organization description
  if (aiInstructions.orgDescription) {
    lines.push("### Product Context");
    lines.push("");
    lines.push("Keep the following product context in mind when generating or reviewing any user-facing wording:");
    lines.push("");
    lines.push(aiInstructions.orgDescription);
    lines.push("");
  }

  // Glossary
  if (glossary.length > 0) {
    lines.push("### Terminology");
    lines.push("");
    lines.push(
      "When writing or translating user-facing text, always use the following approved terms consistently:"
    );
    lines.push("");
    for (const term of glossary) {
      const desc = term.description ? ` — ${term.description}` : "";
      lines.push(`- **${term.term}**${desc}`);
    }
    lines.push("");
    lines.push(
      "Do not use synonyms or alternatives for these terms. They have been chosen for consistency across all languages and surfaces."
    );
    lines.push("");
  }

  // AI Instructions / Tone & Style
  if (aiInstructions.instructions.length > 0) {
    lines.push("### Tone & Style");
    lines.push("");
    lines.push("Follow these rules when writing or reviewing user-facing text:");
    lines.push("");
    for (const instr of aiInstructions.instructions) {
      lines.push(`- ${instr.prompt}`);
    }
    lines.push("");
  }

  return lines.join("\n");
}

function writeToPath(filePath: string, content: string): void {
  const dir = path.dirname(filePath);
  if (!existsSync(dir)) {
    mkdirSync(dir, { recursive: true });
  }
  writeFileSync(filePath, content, "utf-8");
}

export function createSkillsCommand(): Command {
  const skillsCommand = new Command("skills");

  skillsCommand
    .description("Generate wording guidelines skill for Claude Code or Cursor")
    .option("--language <code>", "Language code for glossary terms (defaults to org default)")
    .option("--output <path>", "Output file path (skips interactive prompt, plain markdown)")
    .option("--force", "Force regeneration even if file is recent", false)
    .option("--api-token <token>", "API token (overrides PRISMY_API_TOKEN env var)")
    .action(async (options: ContextCommandOptions) => {
      try {
        // 1. Resolve output paths
        let outputPaths: string[];
        let isSkill: boolean;

        if (options.output) {
          outputPaths = [path.resolve(options.output)];
          isSkill = false;
        } else if (process.env.CI) {
          outputPaths = [path.resolve(`.claude/skills/${SKILL_DIR}/${SKILL_FILE}`)];
          isSkill = true;
        } else {
          const choice = await promptForPaths();
          outputPaths = choice.paths.map((p) => path.resolve(p));
          isSkill = choice.isSkill;
        }

        // 2. Check freshness (skip if all paths are recent)
        if (!options.force) {
          const allFresh = outputPaths.every((p) => existsSync(p) && !isStale(p));
          if (allFresh) {
            Logger.info(
              `Wording guidelines are up to date (less than 24h old). Use --force to regenerate.`
            );
            return;
          }
        }

        // 3. Fetch data
        const apiToken = await AuthService.resolveApiToken(options.apiToken);
        const apiService = new ApiService(apiToken);

        Logger.info("Fetching glossary and AI instructions...");

        const lang = options.language;
        const aiInstructions = await apiService.getAiInstructions(lang);
        const glossaryLang = lang || aiInstructions.language;
        const glossary = await apiService.getGlossary(glossaryLang);

        // 4. Generate and write
        const content = generateMarkdown(glossary, aiInstructions, isSkill);

        for (const outputPath of outputPaths) {
          writeToPath(outputPath, content);
          Logger.success(`Wording guidelines saved to ${outputPath}`);
        }

        Logger.info(`Glossary terms: ${glossary.length}`);
        Logger.info(`AI instructions: ${aiInstructions.instructions.length}`);
      } catch (error) {
        Logger.error(
          `Guidelines generation failed: ${error instanceof Error ? error.message : String(error)}`
        );
        process.exit(1);
      }
    });

  return skillsCommand;
}
